# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fced5cd0ac603955b4d1e974dd91af49b73303ac4871820cac303638d56f316f7fbee25613aa3143fa0170d4aa50b8df2ae3c4738c2b63ead7d689a1ec5f5c

test:
  secret_key_base: 7d030a297fb743d7bafbaa7f46465d6f64cc6c41ae13079a28a8a79f30622ca7552e54fa5c9365aa4ffd486a773a1e90df16589d7fc1b536a26e07893ef9c61c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
